version: "3"
services:
  db:
    image: mysql:8.2.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "OnlineTest"
      MYSQL_USER: "OnlineTest"
      MYSQL_PASSWORD: "OnlineTest123"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: backend_c
    environment:
      MYSQL_HOST: "db"
    ports:
      - "4001:4001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_c
    volumes:
      - /app/node_modules
    ports:
      - "3000:5173"
    tty: true
    depends_on:
      - backend

volumes:
  db:
    driver: local
